### ISSUE TITLE
new ajax error message in account financial

### ISSUE THREAD

**Issue by renepickhardt** [Horndev/zapread.com-issues#56] opened 2018-08-27 11:18 UTC
<img width="1213" alt="bildschirmfoto 2018-08-27 um 13 16 15" src="https://user-images.githubusercontent.com/1926816/44657042-b5654b00-a9fb-11e8-8582-453e9c09997a.png">

**Comment by Horndev** [comment] 2018-08-27 12:42
This is somehow related to #37 I don't see this error.  I saw this error once while debugging, but fixed the cause.  I'll have to investigate.

**Comment by renepickhardt** [comment] 2018-08-27 13:35
I reproduced it for you and looked in firebug. there seems to be an internal server error (HTTP 500 (I thought you make everything 200)) produced by AJAX and jQuery

Request URL: http://www.zapread.com/Manage/GetSpendingEvents
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 205.144.171.180:80
Referrer Policy: no-referrer-when-downgrade
Cache-Control: private, s-maxage=0
Content-Length: 23536
Content-Type: text/html; charset=utf-8
Date: Mon, 27 Aug 2018 13:31:39 GMT
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
X-AspNetMvc-Version: 5.2
X-Frame-Options: SAMEORIGIN
X-Powered-By: ASP.NET
POST /Manage/GetSpendingEvents HTTP/1.1
Host: www.zapread.com
Connection: keep-alive
Content-Length: 408
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://www.zapread.com
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Content-Type: application/json
Referer: http://www.zapread.com/Manage/Financial
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7
Cookie: __RequestVerificationToken=DELETED FOR PRIVACY REASONCS
{"draw":1,"columns":[{"data":"Time","name":"","searchable":true,"orderable":true,"search":{"value":"","regex":false}},{"data":null,"name":"","searchable":true,"orderable":false,"search":{"value":"","regex":false}},{"data":"Amount","name":"","searchable":true,"orderable":false,"search":{"value":"","regex":false}}],"order":[{"column":0,"dir":"asc"}],"start":0,"length":10,"search":{"value":"","regex":false}}

**Comment by Horndev** [comment] 2018-08-27 15:44
> HTTP 500 (I thought you make everything 200)

That's only for the withdraws.  The reason is that I've had "hackers" trying to get money out.  I want to give as little indication that they are failing as possible, and little info on the reason why.  I would be happy for them to think they are past a stage while I continue to block them.

Thanks for the info.  I can't work on this right now, but I'll look into this tonight and correct it.

**Comment by Horndev** [comment] 2018-08-28 00:57
problem found and fixed in https://github.com/Horndev/zapread.com/commit/9accbcabbbd772934a8e1d0d495b371bc49ea549

**Closed by Horndev** 2018-08-28 00:57 UTC
Labels: accounts/users, bug
